apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: REDIS_HOST
              value: redis
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
